# create a Docker image that can run your plugin based on a CloudStack Management server docker image
ARG base
FROM ${base}

ADD server/target/*.jar /usr/share/cloudstack-management/lib
ADD common/target/*.jar /usr/share/cloudstack-management/lib
