ARG SERVER="cloudstack/simulator-jdk"
ARG TAG="latest"
FROM ${SERVER}:${TAG}

ARG LIBPATH="/usr/share/cloudstack-management/lib/"
COPY server/target/*.jar ${LIBPATH}
COPY common/target/*.jar ${LIBPATH}
RUN rm -f ${LIBPATH}/original*.jar
